argoapp:
  appname: argo-ms-refresh
  namespace: argocd
  valuesfile: ~
  project: default
  valuesrepo: ~
  valuesref: HEAD
  repourl: https://gczuczy.github.io//multisources-refreshbug-chart/
  version: ~
  chart: argo-ms-refresh
  relname: ~
  deploymentNamespace: ~
  syncPolicy:
    prune: true
    selfHeal: true
    applOutOfSyncOnly: true
    validate: false

deployment:
  foo: bar

envinfo: ~

